### ISSUE TITLE
Queries regarding Magento2-kount extension

### ISSUE THREAD

**Issue by nithincninan** [swarming/magento2-kount#1]
Team,

We have installed the magento2-kount extension on our latest Magento 2 version. We have some queries regarding this extension:

1) We have 5 websites on our Magento instance. We are only using this extension on 2 websites.  So Please confirm we can use this extension only on two websites and keep disable on the others.

2) We didn't start testing this extension, but we need to make sure that this extension is compatible on M2 latest version(2.2). Please let us know.

Thanks!
Nithin Ninan

**Comment by ytorbyk** [comment]
Hi @nithincninan ,
Yes it's possible to enable/configure the extension per website. 
Yes, it supports Magento 2.2.

**Comment by nithincninan** [comment]
Yurii Torbyk,

Thanks for the update!!! We will try this and let you know the results.

Thanks!
Nithin Ninan

**Comment by duffner** [comment]
Nithin,  did everything work out as expected ?

**Comment by nithincninan** [comment]
@duffner we have just installed the extension on stage instance. We didn't start testing on our stage. will update you once we complete testing.

Thanks!
Nithin Ninan

**Comment by duffner** [comment]
I'm closing this issue as we haven't heard anything back, but please feel free to respond if you have any issues. 

Robert
