### ISSUE TITLE
4.1.0 fails to compile on Magento Clould 2.2.8 CsrfAwareActionInterface not found

### ISSUE THREAD

**Issue by xantek-imc** [swarming/magento2-kount#12]
magento setup:di:compile error
...
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 82.0 MiB
Fatal error:  Interface 'Magento\Framework\App\CsrfAwareActionInterface' not found in /app/vendor/swarming/magento2-kount/Controller/Ens/Index.php on line 15
          Fatal error: Interface 'Magento\Framework\App\CsrfAwareActionInterface' not found in /app/vendor/swarming/magento2-kount/Controller/Ens/Index.php on line 15

**Comment by xantek-imc** [comment]
https://github.com/swarming/magento2-kount/blob/baddc4c5a174796909bfe8cc707624f8213379ce/Controller/Ens/Index.php#L15

**Comment by jcolas15** [comment]
Hello @xantek-imc , 

For Magento < 2.3, please use the extension version 3.1.0.  Interface 'Magento\Framework\App\CsrfAwareActionInterface' isn't available until 2.3.x

**Comment by jcolas15** [comment]
If you are on Magento 2.2.8, 3.2.0 is now available, ^4.0.0 is for Magento ^2.3.x

**Comment by xantek-imc** [comment]
@jcolas15 We were using 3.1 but instructed by Kount to upgrade to the 4 branch knowing we are M2.2.    Commit https://github.com/swarming/magento2-kount/commit/4f974103b32ecd955815a2606b40fb6bf9dc47c7 adds M2.2 to version 4.1.0 in composer.json.  I think composer.json should be corrected or M2.3 only dependencies should not be used.

**Comment by xantek-imc** [comment]
Looks like commit https://github.com/swarming/magento2-kount/commit/b757c962a43aa4d6b3582420907ce14a9a1926c9 reverts to M2.3 support so I consider this issue resolved.
