### ISSUE TITLE
Session has length [128] which is longer than the maximum of [32]

### ISSUE THREAD

**Issue by xantek-imc** [swarming/magento2-kount#15]
https://github.com/swarming/magento2-kount/blob/b757c962a43aa4d6b3582420907ce14a9a1926c9/Model/Session.php#L17

It appears moving from MD5 to SHA512 for hashing session ID break the call to the Kount API

From the Magento kount.log
[2019-08-21 12:24:54] main.ERROR: Exception while making RIS request: Field [SESS] has length [128] which is longer than the maximum of [32]

**Comment by jcolas15** [comment]
Hello @xantek-imc,

Depending on your version of Magento, a new package version is available. 4.2.1 for Magento 2.3.x and 3.2.1 for Magento 2.2.x

**Comment by xantek-imc** [comment]
Issue resolved.  Thank you.
