### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by zexperto** [swarming/magento2-kount#2]
Hello Sir,
I am interested to use your extension 
Do you have any user guide for this extension ?

**Comment by Laura021** [comment]
https://support.kount.com/Developer_Resources/Plugins_and_Libraries/Magento_Extension

**Comment by zexperto** [comment]
Many thanks

**Comment by Nehace40** [comment]
Not able to open user guide.
Please provide user guide link

**Comment by zexperto** [comment]
I just wanted to update the User guide URL
https://support.kount.com/s/article/Download-and-Install-Magento-Extensions
here is the installation and user guides
