### ISSUE TITLE
Google Update Impacts Kount Services

### ISSUE THREAD

**Issue by vbuck** [swarming/magento2-kount#20]
I received an email report today from Kount about the Google Chrome February 2020 rollout of security policy changes with respect to 3rd-party cookie management.

References:
* https://techcommunity.microsoft.com/t5/microsoft-stream-forum/upcoming-chrome-changes-and-breaking-issues-with-iframes/m-p/909679
* https://www.chromium.org/updates/same-site

The email states:
> _If you are using the iFrame, you will see code such as:_
> _<iframe .... src="ssl.kaptcha.com/index.htm". If this is the case, you are using the old methodology._

This "old methodology" is what is being used in the Magento 2 extension right now.

The email advises that this practice be converted to the JavaScript SDK style implementation:
* https://kount.github.io/docs/dc-web-browser/

Do you have any plans to support this officially in the extension?

**Comment by vbuck** [comment]
Following up on this. I received another notification today from your team, which stated:

> _Kount has discovered a method that allows for device collection processes to continue uninterrupted using the iFrame for Chrome v80 and v81. What this means is that Chrome v80 will no longer impact the device data collection._

So the urgency has been reduced, but eventually this will need to be addressed in your Magento 2 integration. By this message I assume it means you have either found a way to preserve the iframe method from your side, or else the severity of the Google update was not quite what you had first thought (the latter here is actually how _I_ interpreted their bulletin which I referenced in my opening comment).

But my question still remains: if the JavaScript SDK is the preferred method of DDC integration, do you have a roadmap to start using it in this extension?

**Comment by jcolas15** [comment]
Hello @vbuck, 

Versions 3.2.2 and 4.2.2 have been released.  Please install latest versions to account for your findings.

**Comment by vbuck** [comment]
Thanks @jcolas15. I've reviewed #21 and can confirm that it appears to solve for this issue. I'll work on rolling it out for customers, but I will close the issue for now.
