### ISSUE TITLE
Shipping method is not guaranteed to be an object

### ISSUE THREAD

**Issue by ngreimel** [swarming/magento2-kount#30]
An error can occur during setting of the shipping method when `Magento\Sales\Model\Order::getShippingMethod(true)` returns a falsy value rather than the expected DataObject.

In Magento 2.3.x, the getShippingMethod method has a condition which (irrespective of the `$asObject` argument) will return a non-object if `!$shippingMethod`. A safer way to handle this data should be explored to prevent exceptions in Kount\Model\Ris\Inquiry\Builder\Order.

**Comment by ngreimel** [comment]
`Fatal Error: 'Uncaught Error: Call to a member function getData() on null in /app/vendor/swarming/magento2-kount/Model/Ris/Inquiry/Builder/Order.php:150`

**Comment by ion497** [comment]
Hi @ngreimel, thanks for reporting this. We'll review and update this issue accordingly.

**Comment by gaugeroque** [comment]
Yes I have the same issue with an order that only has virtual products.

**Comment by mohammedceil** [comment]
I faced the similar issue yesterday and i had a workaround after reviewing the old version. In new version 4.2.8 validation is not properly handled compared to the old version 3.2.2

Old version
<img width="839" alt="Screenshot 2020-08-12 at 7 44 46 PM" src="https://user-images.githubusercontent.com/28587492/90108221-95093500-dd67-11ea-978b-44d80ab805c7.png">


New version
<img width="839" alt="Screenshot 2020-08-12 at 7 45 42 PM" src="https://user-images.githubusercontent.com/28587492/90108245-9f2b3380-dd67-11ea-863c-6a84d4282f62.png">

Work around for the new version
<img width="839" alt="Screenshot 2020-08-12 at 7 53 19 PM" src="https://user-images.githubusercontent.com/28587492/90108274-ad794f80-dd67-11ea-920e-88aa930c655d.png">

I tried to push a branch with a fix but i am not authorised to it. 
remote: Permission to swarming/magento2-kount.git denied to mohammedceil.
fatal: unable to access 'https://github.com/swarming/magento2-kount.git/': The requested URL returned error: 403

Developer team can take this if it is helpful.

Thanks for the useful module guys.

**Comment by 417Turner** [comment]
Thanks for calling this out, we have implemented a solution/fix and the updated versions are as follows:


1. Versions 3.2.9 have been released for Magento 2.2.x

> composer require swarming/magento2-kount:3.2.9


2. Version 4.2.9 have been released for Magento 2.3.x

> composer require swarming/magento2-kount:4.2.9
