### ISSUE TITLE
Order not appear in Customer Account if the status = Review

### ISSUE THREAD

**Issue by zexperto** [swarming/magento2-kount#4]
Hello ,
We have a problem in the order list in Magento Customer Account, If the order status is "Review" and it is not yet approved/declined etc.. from the Kount side, The customer cannot see the order in Magento customer account , is there any configuration to allow the customer to see the order in Customer Account?

**Comment by duffner** [comment]
Hello @zexperto, we received your request from Kount, thank you for your submission.  We added this as a new feature.  You can now enable the display of Review and Fraud orders within the Magento Admin panel.  Please upgrade the extension to gain access to this feature.

**Comment by william-hiko** [comment]
Thank you for this new feature

**Comment by zexperto** [comment]
Many thanks, it is working
