### ISSUE TITLE
Source class "\Kount_Log_Factory_" for "\Kount_Log_Factory_Logger" generation does not exist.

### ISSUE THREAD

**Issue by qgor** [swarming/magento2-kount#5]
Hi,

I like do put the module on my local dev and try it out. Pulled down the source and ran setup:upgrade successfully. However getting this when setup:di.compile

[RuntimeException]
  Source class "\Kount_Log_Factory_" for "\Kount_Log_Factory_Logger" generation does not exist.

Any suggestions on resolving the error?

**Comment by duffner** [comment]
@qgor, did you install the module via composer?

**Comment by qgor** [comment]
Do I have to use composer to install the module? Just the source code doesn't work? Are there other dependencies?

**Comment by duffner** [comment]
Qgor,  yes since the Kount SDK is a dependency of our module and it’s best practice for installation.

**Comment by qgor** [comment]
OK, I'll give it a try. Thanks.

**Comment by duffner** [comment]
Let us know if you need any help!  Sincerely, Robert
