### ISSUE TITLE
Constant set for USD

### ISSUE THREAD

**Issue by qgor** [swarming/magento2-kount#7]
Hi, 

I'm integrating Kount using your extension for a Canadian client. The default currency is set to CAD. After the payment is completed, Kount rejects the order due to lack of currency rate (Swarming\Kount\Model\Ris\Inquiry\Builder\Order->convertAndRoundAmount). After looking into error, it looks like a constant is set in that class (Swarming\Kount\Model\Ris\Inquiry\Builder\Order) that causes the currency conversion. I don't see this is configurable and I should not change the constant directly in the code (since it's using composer and source is in the vendor folder). What should I do to bypass the currencyConvert call? 

Thanks,
Patrick

**Comment by duffner** [comment]
@qgor, If I recall correctly we do not support any other base currency outside of the USD. However, I'd recommend filing a ticket with support@kount.com as a first step. They may ask us to assist you towards resolution.   If I hear back, I will follow up with you in this ticket. 

Thanks 
Robert

**Comment by qgor** [comment]
Thanks for that. I'll reach out to support

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by duffner** [comment]
Hello @qgor, the develop branch now includes a fix for the conversion of currencies.  May I ask if the Global currency is CAD or do you override this value by website?

**Comment by qgor** [comment]
Hi Robert,

The implementation for our client this time their currency is CAD. The problem we're facing is the base/default currency is a constant baked in the code with USD which forces Magento to lookup for the currency exchange. As a business that solely conducting business within Canada this is unnecessary. If the base/default currency can be configurable, in our case CAD, to skip the currency exchange process. This will resolve our issue.

Thanks,

Patrick

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by duffner** [comment]
Patrick, 

What you are stating has been added to the develop branch of this repository

**Comment by qgor** [comment]
Hi Robert,

This implementation we're doing is a Canadian base retailer and their business will be all in CAD. We're hoping to see the currency constant that's baked in the code, which set to USD, can be configurable. This will avoid the conversion which Magento attempt to lookup the exchange rate. We like to avoid this.

Thanks,

Patrick

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by qgor** [comment]
Hi Robert,

Thanks for the email. Sorry about duplicating previous message. Will I able to pull in the dev branch using composer?


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by duffner** [comment]
Did everything work out with our changes in DEV
