### ISSUE TITLE
Secret material in defaults

### ISSUE THREAD

**Issue by andrewhowdencom** [swarming/magento2-kount#9]
Hola,

This might be  a wontfix, but it looks like there's a random password in the defaults: 

https://github.com/swarming/magento2-kount/blob/master/etc/config.xml#L16

Cheers,

**Comment by duffner** [comment]
@andrewhowdencom, while we definitely agree this shouldn't be in here, it's an unfortunate requirement of the Kount SDK.

**Comment by andrewhowdencom** [comment]
Closing ^^
